# type4_alerts.py — PRE_BREAKOUT + CATALYST alert functions
# Generated by temp_add_type4_alerts_v2.py
# Imported by cloud_alert_engine.py
# Location: multibagger-alerts/type4_alerts.py

import hashlib as _hl
import json as _js
import os as _os
import re as _re2
from datetime import datetime as _dt, timedelta as _td


def _si(v):
    try:
        return int(float(v or 0))
    except (TypeError, ValueError):
        return 0


def build_prebreakout_alert(load_fn, cs_map_in=None) -> str:
    """
    TYPE 4a: EARLY BUY
    Stocks where FII/Revenue/VCP signals firing but RS not yet top-quartile.
    These are the stocks that WILL be flagged next run -- catch them BEFORE
    the 25% move.
    """
    ea = load_fn("early_alerts")
    if ea.empty:
        return ""
    ea.columns = [c.strip() for c in ea.columns]

    if "ALERT_TYPE" not in ea.columns:
        return ""
    pb = ea[ea["ALERT_TYPE"].astype(str).str.upper() == "PRE_BREAKOUT"].copy()
    if pb.empty:
        return ""

    sev_order = {"VERY_HIGH": 0, "HIGH": 1, "MEDIUM": 2}
    if "SEVERITY" in pb.columns:
        pb["_sv"] = pb["SEVERITY"].map(sev_order).fillna(3)
        pb = pb.sort_values("_sv").head(8)

    # Build composite map if not passed in
    cs_map = cs_map_in or {}
    if not cs_map:
        cs = load_fn("composite")
        if not cs.empty:
            cs.columns = [c.strip() for c in cs.columns]
            for _, cr in cs.iterrows():
                s = str(cr.get("NSE_SYMBOL", "")).strip().upper()
                if s:
                    cs_map[s] = {
                        "q":     _si(cr.get("Q_SCORE", 0)),
                        "g":     _si(cr.get("G_SCORE", 0)),
                        "s":     _si(cr.get("S_SCORE", 0)),
                        "tier":  str(cr.get("TIER", "")).strip(),
                        "entry": str(cr.get("ENTRY_ZONE", "")).strip(),
                        "sl":    str(cr.get("STOP_LOSS", "")).strip(),
                    }

    sym_col = next((c for c in pb.columns if c.upper() in ("NSE_SYMBOL", "SYMBOL")), None)
    det_col = next((c for c in pb.columns if c.upper() in ("ALERT_DETAIL", "DETAIL", "DESCRIPTION")), None)
    sev_col = next((c for c in pb.columns if c.upper() == "SEVERITY"), None)

    lines_out = [
        "\u26a1 <b>EARLY BUY</b>",
        "<i>Leading signals firing BEFORE price moves</i>",
        "",
    ]

    for _, row in pb.iterrows():
        sym  = str(row.get(sym_col, "")).strip() if sym_col else ""
        det  = str(row.get(det_col, "")).strip()[:110] if det_col else ""
        sev  = str(row.get(sev_col, "")).strip() if sev_col else ""
        icon = "\U0001f525" if sev == "HIGH" else "\U0001f4cc"
        cd   = cs_map.get(sym.upper(), {})
        q, g, s = cd.get("q", 0), cd.get("g", 0), cd.get("s", 0)
        tier = cd.get("tier", "")
        en   = _re2.findall(r"\u20b9([\d,]+)", cd.get("entry", ""))
        e_str = ("\u20b9" + en[0] + "\u2013" + en[1]) if len(en) >= 2 else ("\u20b9" + en[0] if en else "")
        sl_m  = _re2.search(r"\u20b9([\d,]+(?:\.\d+)?)", cd.get("sl", ""))
        sl_str = "SL\u20b9" + sl_m.group(1) if sl_m else ""
        price_str = (" | " + e_str + " " + sl_str).strip() if e_str else ""
        lines_out.append(
            icon + " <code>" + sym.ljust(10) + "</code> [" + tier + "]"
            + price_str
        )
        lines_out.append("   Q:" + str(q) + " G:" + str(g) + " S:" + str(s))
        lines_out.append("   <i>" + det[:100] + "</i>")
        lines_out.append("")

    if len(lines_out) <= 3:
        return ""

    lines_out.append("<i>Watch only -- no position until engine confirms STRONG/PRIME.</i>")
    return "\n".join(lines_out)


def build_catalyst_alert(load_fn) -> str:
    """
    TYPE 4b: CATALYST ALERT
    Fresh ORDER_WIN / REG_APPROVAL / MA_EVENT on quality stocks (Q>=15).
    Deduplicated 48h via seen_hashes.json.
    """
    ev = load_fn("events")
    cs = load_fn("composite")
    if ev.empty or cs.empty:
        return ""

    ev.columns = [c.strip() for c in ev.columns]
    cs.columns = [c.strip() for c in cs.columns]

    QUALITY_TIERS = {"PRIME", "STRONG", "WATCHLIST_CONFIRMED"}
    cs["NSE_SYMBOL"] = cs["NSE_SYMBOL"].astype(str).str.strip().str.upper()
    quality_map = {}
    for _, row in cs.iterrows():
        sym = row["NSE_SYMBOL"]
        tier = str(row.get("TIER", "")).strip()
        q = _si(row.get("Q_SCORE", 0))
        if tier in QUALITY_TIERS and q >= 15:
            quality_map[sym] = {
                "tier":  tier,
                "q":     q,
                "g":     _si(row.get("G_SCORE", 0)),
                "score": _si(row.get("COMPOSITE_BALANCED", 0)),
                "entry": str(row.get("ENTRY_ZONE", "")).strip(),
            }

    if not quality_map:
        return ""

    # Normalise event column names
    renames = {}
    for c in ev.columns:
        cu = c.upper().replace(" ", "_")
        if cu in ("DATE", "EVENT_DATE", "ANN_DATE"):         renames[c] = "DATE"
        elif cu in ("NSE_SYMBOL", "SYMBOL", "NSE_CODE"):     renames[c] = "NSE_SYMBOL"
        elif cu in ("EVENT_TYPE", "CATEGORY", "TYPE"):       renames[c] = "EVENT_TYPE"
        elif cu in ("SUBJECT", "HEADLINE", "DESCRIPTION"):   renames[c] = "SUBJECT"
        elif cu in ("COMPANY", "COMPANY_NAME", "NAME"):      renames[c] = "COMPANY"
    if renames:
        ev = ev.rename(columns=renames)

    CATALYST_TYPES = {"ORDER_WIN", "REG_APPROVAL", "MA_EVENT", "RESULTS_BEAT", "CAPEX_ANNOUNCE"}
    ev_f = ev.copy()
    if "EVENT_TYPE" in ev.columns:
        ev_f = ev[ev["EVENT_TYPE"].astype(str).str.upper().str.strip().isin(CATALYST_TYPES)].copy()
    if "NSE_SYMBOL" not in ev_f.columns:
        return ""

    ev_f["NSE_SYMBOL"] = ev_f["NSE_SYMBOL"].astype(str).str.strip().str.upper()
    ev_f = ev_f[ev_f["NSE_SYMBOL"].isin(quality_map)].copy()
    if ev_f.empty:
        return ""

    if "DATE" in ev_f.columns:
        import pandas as _pd2
        ev_f["DATE"] = _pd2.to_datetime(ev_f["DATE"], errors="coerce")
        cutoff = _dt.now() - _td(days=30)
        ev_f = ev_f[ev_f["DATE"] >= cutoff].sort_values("DATE", ascending=False)
    if ev_f.empty:
        return ""

    # Dedup via seen_hashes.json
    hash_file = _os.path.join(_os.path.dirname(__file__), "seen_hashes.json")
    try:
        seen = _js.loads(open(hash_file).read()) if _os.path.exists(hash_file) else {}
    except Exception:
        seen = {}
    now_ts = _dt.now().timestamp()
    seen   = {k: v for k, v in seen.items() if now_ts - v < 172800}

    EV_ICON = {
        "ORDER_WIN":       "\U0001f7e2",
        "REG_APPROVAL":    "\U0001f7e1",
        "MA_EVENT":        "\U0001f535",
        "RESULTS_BEAT":    "\U0001f4c8",
        "CAPEX_ANNOUNCE":  "\U0001f3d7",
    }

    lines_out = ["\U0001f4e2 <b>CATALYST ALERT</b>", ""]
    new_seen  = {}
    shown     = 0

    for _, row in ev_f.iterrows():
        sym  = str(row.get("NSE_SYMBOL", "")).strip()
        evtp = str(row.get("EVENT_TYPE", "")).strip().upper()
        subj = str(row.get("SUBJECT", "")).strip()[:80]
        dt_s = str(row.get("DATE", ""))[:10]
        key  = _hl.md5((sym + evtp + subj[:30]).encode()).hexdigest()[:16]
        if key in seen:
            continue
        cd    = quality_map.get(sym, {})
        score = cd.get("score", 0)
        tier  = cd.get("tier", "")
        q, g  = cd.get("q", 0), cd.get("g", 0)
        icon  = EV_ICON.get(evtp, "\U0001f4cc")
        lines_out.append(icon + " <b>" + sym + "</b> [" + tier + "] <b>" + str(score) + "</b>  Q:" + str(q) + " G:" + str(g))
        lines_out.append("   " + evtp.replace("_", " ") + " \u2014 " + subj)
        lines_out.append("   <i>" + dt_s + "</i>")
        lines_out.append("")
        new_seen[key] = now_ts
        shown += 1
        if shown >= 5:
            break

    if shown == 0:
        return ""

    seen.update(new_seen)
    try:
        with open(hash_file, "w") as hf:
            _js.dump(seen, hf)
    except Exception:
        pass

    lines_out.append("<i>Catalyst on quality stock (Q\u226515) \u2014 " + str(shown) + " new event(s)</i>")
    return "\n".join(lines_out)
